Added custom boot option support in unionfs. Also added unionfs support to arch2sqfs script.

diff --git a/custom-config/usr/bin/arch2sqfs b/custom-config/usr/bin/arch2sqfs
--- a/custom-config/usr/bin/arch2sqfs
+++ b/custom-config/usr/bin/arch2sqfs
@@ -179,13 +179,21 @@ removelist()
 	mkdir -p $UNION
 	mkdir -p $CHANGES
 	
-	
+	if [ "$(cmdline_parameter aufs)" ]; then
 	modprobe aufs
     if [ $? -ne 0 ]; then
 	echo "Error loading Union filesystem module."
 	exit 1
     fi
 	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
+	else
+	modprobe unionfs
+	if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+    mount -t unionfs -o dirs=$CHANGES=rw:$IMAGES/$MODULE=ro none $UNION
+	fi
 	#sync
 	
 	cat $2 | grep -v "^#" | while read PKGNAME; do
@@ -228,12 +236,21 @@ addlist()
 	mkdir -p $UNION
 	mkdir -p $CHANGES
 	
+	if [ "$(cmdline_parameter aufs)" ]; then
 	modprobe aufs
     if [ $? -ne 0 ]; then
 	echo "Error loading Union filesystem module."
 	exit 1
     fi
 	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
+	else
+	modprobe unionfs
+	if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+    mount -t unionfs -o dirs=$CHANGES=rw:$IMAGES/$MODULE=ro none $UNION
+	fi
 	#sync
 	
 	cat $2 | grep -v "^#" | while read PKGNAME; do
@@ -359,7 +376,22 @@ updateonly()
 	mkdir -p $UNION
 	MODULE=$(basename "$1" .sqfs).sqfs
 	cp -aR /var/lib/pacman/local/* $DBPATH
+	
+    if [ "$(cmdline_parameter aufs)" ]; then
+	modprobe aufs
+    if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
 	mount -t aufs -o br:$CHANGES=rw:$DB=rr aufs $UNION
+	else
+	modprobe unionfs
+	if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+    mount -t unionfs -o dirs=$CHANGES=rw:$DB=ro none $UNION
+	fi
 	#sync
 	pacman -Syu --noconfirm -d -r $UNION
 	
@@ -405,6 +437,21 @@ update()
 	mkdir -p $CHANGES
 	mkdir -p $UNION
 
+	if [ "$(cmdline_parameter aufs)" ]; then
+	modprobe aufs
+    if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
+	else
+	modprobe unionfs
+	if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+    mount -t unionfs -o dirs=$CHANGES=rw:$IMAGES/$MODULE=ro none $UNION
+	fi
 	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
 	if [ $? -ne 0 ]; then 
 	echo "Error building union."
