Updated mkarchiso script. Changes are from Francesco Piccinno archpwn project.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/archiso/mkarchiso b/archiso/mkarchiso
--- a/archiso/mkarchiso
+++ b/archiso/mkarchiso
@@ -15,7 +15,11 @@ KERNEL="/etc/mkinitcpio.d/kernel26.kver"
 ROOT_MOD="$(ls -1 $(pwd)/list | head -1)"
 #MODULES=$(ls -1 $(pwd)/list)
 CDNAME="archiso-live"
-LIVELINUX="../../linux-live/initrd"
+LINUXLIVE="../../linux-live/initrd"
+
+error () { echo -e "\033[1;31;40m!!! \033[1;37;40m$@\033[1;0m"; }
+warn ()  { echo -e "\033[1;33;40m*** \033[1;37;40m$@\033[1;0m"; }
+info () { echo -e "\033[1;32;40m>>> \033[1;37;40m$@\033[1;0m"; }
 
 if [ -f $(pwd)/config ]; then
 . $(pwd)/config
@@ -50,6 +54,7 @@ usage ()
     echo " commands:"
     echo "     install <working dir>        : install packages to the working dir"
     echo "     squash <working dir>         : generate a squashfs image of the installed root"
+    echo "     imgprepare <working dir>     : prepare the image"
     echo "     img <working dir> <image name> : build an image from the working directory"
     echo "     all <working dir> <image name> : perform all of the above, in order"
     exit $1
@@ -76,7 +81,7 @@ while getopts 'i:P:b:M:m:a:t:c:nfvh' arg; do
 done
 
 #trim spaces
-PKGLIST="$(echo $MODULES)"
+#PKGLIST="$(echo $MODULES)"
 
 shift $(($OPTIND - 1))
 echo "ARGS: $@"
@@ -85,7 +90,7 @@ echo "ARGS: $@"
 
 # do UID checking here so someone can at least get usage instructions
 if [ "$EUID" != "0" ]; then
-    echo "error: This script must be run as root."
+    error "error: This script must be run as root."
     exit 1
 fi
 
@@ -96,15 +101,16 @@ imgname=""
 case "${command_name}" in
     install) work_dir="${2}" ;;
     squash) work_dir="${2}" ;;
+    imgprepare) work_dir="${2}" ;;
     img) work_dir="${2}"; imgname="${3}" ;;
     all) work_dir="${2}"; imgname="${3}" ;;
-    *) echo "invalid command name '${command_name}'"; usage 1 ;;
+    *) warn "invalid command name '${command_name}'"; usage 1 ;;
 esac
 
 if [ "x${BOOT}" = "x" ]; then BOOT="syslinux"; fi
 
-[ "x${imgname}" = "x" ] && (echo "Bootable image name must be specified" && usage 1)
-[ "x${work_dir}" = "x" ] && (echo "please specify a working directory" && usage 1)
+[ "x${imgname}" = "x" ] && (warn "Bootable image name must be specified" && usage 1)
+[ "x${work_dir}" = "x" ] && (warn "please specify a working directory" && usage 1)
 
 if [ "${NOLZMA}" = "n" ]; then
 	EXT="sqfs"
@@ -123,6 +129,7 @@ echo "        working directory:   ${work_dir}"
 echo "               image name:   ${imgname}"
 echo "               image type:   ${IMG_TYPE}"
 echo "		  squashfs type:   ${EXT}"
+sleep 1
 
 IMGROOT="${work_dir}/img"
 union="${work_dir}/union"
@@ -134,8 +141,8 @@ CDROOT="$(pwd)/cd-root"
 
 _kversion ()
 {
-    source ${INSTROOT}${KERNEL}
-    #source ${INSTROOT}/etc/mkinitcpio.d/kernel26slax.kver
+    #source ${INSTROOT}${KERNEL}
+    source ${INSTROOT}/etc/mkinitcpio.d/kernel26.kver
     echo ${ALL_kver}
 }
 
@@ -156,7 +163,8 @@ remove()
 command_install () {
     echo "====> Installing/building image root"
     if [ -e "${work_dir}" -a "${FORCE}" = "n" ]; then
-        echo "error: Working dir '${work_dir}' already exists, aborting."
+        error "error: Working dir '${work_dir}' already exists, aborting."
+	error "       set FORCE to 'y' to overwrite"
         exit 1
     fi
 
@@ -169,21 +177,16 @@ command_install () {
     mkdir -p ${IMGROOT}/${CDNAME}/{modules,optional,rootcopy}
     touch ${IMGROOT}/${CDNAME}/livecd.sgn
 	cp -af ${CDROOT}/* "${IMGROOT}"
-    ln -sf ${LIVELINUX} initrd
-    cd initrd
-    ./initrd_create $CDNAME
-    cd ../
-    mv -f initrd/initrd.lzm "${IMGROOT}"
 
     modprobe aufs
     if [ $? -ne 0 ]; then
-	echo "Error loading Union filesystem module."
+	error "Error loading Union filesystem module."
 	exit 1
     fi
 
     mount -t aufs -o br:${lastbr}=rw aufs ${union}
     if [ $? -ne 0 ]; then 
-	echo "Error mounting $UNION."
+	error "Error mounting $UNION."
 	exit 1
     fi
 
@@ -208,13 +211,18 @@ command_install () {
 
 	cat  "$(pwd)/list/${mod}.list" | grep -v "^#" | while read pkgname; do
 		echo "   Installing package $pkgname"
-		pacman -S -f --noprogressbar --needed --noconfirm --config "${PACMANCONF}" -r "$union" $pkgname
+		pacman -S -f --noprogressbar --needed --noconfirm --config "${PACMANCONF}" -r "$union" $pkgname | tee current.log
+		
+		if [ $? -ne 0 ]; then
+                    warn "Package $pkgname not correctly installed"
+                    cat current.log >> errors.log
+            	fi
 	done
 	
 	if [ -e "$(pwd)/list/${mod}.removelist" ]; then
 	cat "$(pwd)/list/${mod}.removelist" | grep -v "^#" | while read pkgname; do
-		echo "	Removeing package $pkgname"
-		pacman -R -d -n --noprogressbar --needed --noconfirm --config "${PACMANCONF}" -r "$union" $pkgname
+		info "	Removeing package $pkgname"
+		pacman -R -d -n --noprogressbar --needed --noconfirm --config "${PACMANCONF}" -r "$union" $pkgname &> /dev/null
 	done
 	fi
 	
@@ -230,16 +238,16 @@ command_install () {
     # remove the initcpio images that were generated for the host system
     find "${union}/boot" -name *.img -delete
 
-    echo "Creating default home directory"
-    install -d -o1001 -g100 -m0755 "${union}/home/arch"
+    #echo "Creating default home directory"
+    #install -d -o1001 -g100 -m0755 "${union}/home/arch"
 	
-	if [ -d "${OVERLAY}/home/arch" ]; then
-		chown -R arch:users "${OVERLAY}/home/arch"
-		chmod -R 755 "${OVERLAY}/home/arch"
-	fi
+    #if [ -d "${OVERLAY}/home/arch" ]; then
+    #	chown -R arch:users "${OVERLAY}/home/arch"
+    #	chmod -R 755 "${OVERLAY}/home/arch"
+    #fi
 
     # Cleanup
-    echo "Cleaning up image root files..."
+    info "Cleaning up image root files..."
     find "${union}" -name *.pacnew -name *.pacsave -name *.pacorig -delete
 
     # delete a lot of unnecessary cache/log files
@@ -255,16 +263,16 @@ command_install () {
 
     # copy over kernel and grub configs for boot
 	if [ "$BOOT" = "grub" -o "$BOOT" = "grub-gfx" ]; then
-		if [ -e "${union}/boot" -a -e "${OVERLAY}/boot" ]; then
+		if [ -e "${union}/boot" ]; then
 			#rm -rf "${IMGROOT}/boot"
 			cp -rf "${union}/boot" "${IMGROOT}"
-			cp -rf "${OVERLAY}/boot" "${IMGROOT}"
+			#cp -rf "${OVERLAY}/boot" "${IMGROOT}"
 		fi
 	else
-		if [ -e "${union}/boot" -a -e "${OVERLAY}/boot" ]; then
+		if [ -e "${union}/boot" ]; then
 			#rm -rf "${IMGROOT}/boot"
 			cp -rf "${union}/boot" "${IMGROOT}"
-			cp -rf "${OVERLAY}/boot" "${IMGROOT}"
+			#cp -rf "${OVERLAY}/boot" "${IMGROOT}"
 			rm -rf "${IMGROOT}/boot/grub"
 		fi
 	fi
@@ -274,79 +282,117 @@ command_install () {
    		cp -r "$(pwd)/isolinux" "${IMGROOT}"
    fi
 
-pacman -Q -r ${union} > ${PKGFILE}
+   pacman -Q -r ${union} > ${PKGFILE}
 
-# Unmount union
-echo "Unmounting union."
-umount -l ${union}
+   # Unmount union
+   info "Unmounting union."
+   umount -l ${union}
 
-echo "Updating kernel module dependencies"
-kernelver=$(_kversion)
-depmod -a -b "${INSTROOT}" "${kernelver}"
+   info "Updating kernel module dependencies"
+   kernelver=$(_kversion)
+   depmod -a -b "${INSTROOT}" "${kernelver}"
 	
-# Clean up unionfs whiteout files
-#echo "Removing unionfs .wh. files."
-find ${moduledir} -type f -name ".wh.*" -exec rm {} \;
-find ${moduledir} -type d -name ".wh.*" -exec rm -rf {} \;
+   # Clean up unionfs whiteout files
+   #echo "Removing unionfs .wh. files."
+   find ${moduledir} -type f -name ".wh.*" -exec rm {} \;
+   find ${moduledir} -type d -name ".wh.*" -exec rm -rf {} \;
 
-    # TODO: this might belong somewhere else
-    #mkdir -p "${IMGROOT}/addons"
-    #if [ -d "${ADDON_DIR}" ]; then
-    #    echo "Copying addons from ${ADDON_DIR}..."
-    #    cp -r ${ADDON_DIR}/* "${IMGROOT}/addons"
-    #fi
+   # TODO: this might belong somewhere else
+   #mkdir -p "${IMGROOT}/addons"
+   #if [ -d "${ADDON_DIR}" ]; then
+   #    echo "Copying addons from ${ADDON_DIR}..."
+   #    cp -r ${ADDON_DIR}/* "${IMGROOT}/addons"
+   #fi
 
+}
+
+command_overlay () {
     # always make an addon out of DEF_CONFIG_DIR
-    echo "Creating default-config addon..."
+    info "Creating overlay default addon..."
+
     if [ "${QUIET}" = "y" ]; then
         /sbin/mksquashfs "${OVERLAY}" "${IMGROOT}/${CDNAME}/optional/overlay.${EXT}" -noappend ${OPTION} >/dev/null
     else
 	/sbin/mksquashfs "${OVERLAY}" "${IMGROOT}/${CDNAME}/optional/overlay.${EXT}" -noappend ${OPTION}
     fi
 	
-	chmod 0444 "${IMGROOT}/${CDNAME}/optional/overlay.${EXT}"
+    chmod 0444 "${IMGROOT}/${CDNAME}/optional/overlay.${EXT}"
 }
 
 # Squash is the next step.
 command_squash () {
-    echo "====> Generating SquashFS image"
-echo "Creating modules procede..."
-start=$(date +%s)
+    info "Generating SquashFS image"
+    info "Creating modules procede..."
+
+    start=$(date +%s)
+
     if [ -d "${MODULESCOPY}" ]; then
-		cp -r ${MODULESCOPY}/* "${IMGROOT}/${CDNAME}/modules"
+	cp -r ${MODULESCOPY}/* "${IMGROOT}/${CDNAME}/modules"
     fi
 
-for DIR in $MODULES; do
+    for DIR in $MODULES; do
 	MOD="$(basename $DIR).${EXT}"
-	echo "building $MOD"
-	/sbin/mksquashfs ${moduledir}/$DIR ${moduleplace}/$MOD -noappend ${OPTION} > /dev/null
+	info "Building module $MOD"
+	if [ "${QUIET}" = "y" ]; then
+            /sbin/mksquashfs ${moduledir}/$DIR ${moduleplace}/$MOD -noappend ${OPTION} > /dev/null
+        else
+            /sbin/mksquashfs ${moduledir}/$DIR ${moduleplace}/$MOD -noappend ${OPTION}
+        fi
 	chmod 0444 ${moduleplace}/$MOD
-done
+    done
+
     minutes=$(echo $start $(date +%s) | awk '{ printf "%0.2f",($2-$1)/60 }')
-    echo "Modules creation done in $minutes minutes."
+    info "Modules creation done in $minutes minutes."
 }
 
 # Finally, make the image.
-command_img () {
-    echo "====> Making bootable image"
+command_imgprepare () {
+    info "Making compressed initrd ( assuming ../linux-live/initrd/initrd_create )"
+    pushd .
+    cd $LINUXLIVE
+
+    if [ $? -ne 0 ]; then
+        error "Cannot chdir into ../linux-live/initrd"
+        exit -1
+    fi
+
+    ./initrd_create $CDNAME
+
+    if [ $? -ne 0 ]; then
+        error "Error while creating initrd.lzm"
+        exit -1
+    fi
+
+    popd
+
+    info "Moving initrd.lzm to $IMGROOT"
+    mv -f $LINUXLIVE/initrd.lzm $IMGROOT/
+
+    if [ $? -ne 0 ]; then
+        error "Error while copying initrd.lzm"
+        exit -1
+    fi
+
+    info "Making bootable image"
+
     if [ -e "${imgname}" ]; then
         if [ "${FORCE}" = "y" ]; then
-            echo "Removing existing bootable image..."
+            info "Removing existing bootable image..."
             rm -rf "${imgname}"
         else
-            echo "error: Image '${imgname}' already exists, aborting."
+            error "error: Image '${imgname}' already exists, aborting."
             exit 1
         fi
     fi
     if [ ! -e "${CPIOCONFIG}" ]; then
-        echo "error: mkinitcpio config '${CPIOCONFIG}' does not exist, aborting."
+        error "error: mkinitcpio config '${CPIOCONFIG}' does not exist, aborting."
         exit 1
     fi
 
     kernelver=$(_kversion)
     basedir=${INSTROOT}
     [ "${INSTROOT:0:1}" != "/" ] && basedir="$(pwd)/${INSTROOT}"
-    echo "Generating initcpio for image..."
+    info "Generating initcpio for image..."
     if [ "${QUIET}" = "y" ]; then
         mkinitcpio -c "${CPIOCONFIG}" -b "${basedir}" -k "${kernelver}" -g "${IMGROOT}/boot/archlive.img" >/dev/null
         ret=$?
@@ -355,9 +401,14 @@ command_img () {
         ret=$?
     fi
     if [ $ret -ne 0 ]; then
-        echo "error: initcpio image creation failed..."
+        error "error: initcpio image creation failed..."
         exit 1
     fi
+}
+
+# Finally, make the image.
+command_img () {
+
 	
 	bootflags=""
 	if [ "$BOOT" = "grub" -o "$BOOT" = "grub-gfx" ]; then
@@ -367,7 +418,7 @@ command_img () {
 		pacman -Q grub-gfx >/dev/null 2>&1
 		tst=$(($tst + $?))
 		if [ $tst -ge 2 ]; then
-			echo "grub or grub-gfx not found on host system. Cannot install!"
+			error "grub or grub-gfx not found on host system. Cannot install!"
 			exit 1
 		fi
 	
@@ -377,7 +428,7 @@ command_img () {
 		bootflags="-b boot/grub/stage2_eltorito"
 	elif [ "$BOOT" = "syslinux" ]; then
 		if ! pacman -Qi syslinux >/dev/null 2>&1; then
-			echo "$BOOT not found on host system. Cannot install!"
+			error "$BOOT not found on host system. Cannot install!"
 			exit 1
 		fi
 		
@@ -399,14 +450,14 @@ command_img () {
 	fi
 	
     if [ "$IMG_TYPE" == "disk" ]; then
-        echo "Creating DISK image..."
+        info "Creating DISK image..."
         mkusbimg "${IMGROOT}" "${imgname}"
     elif [ "$IMG_TYPE" = "iso" ]; then
-        echo "Creating ISO image..."
+        info "Creating ISO image..."
         qflag=""
         #[ "${QUIET}" = "y" ] && qflag="-q"
         mkisofs ${qflag} -r -l $bootflags -uid 0 -gid 0 \
-			-input-charset utf-8 -p "prepared by mkarchiso" \
+	    -input-charset utf-8 -p "prepared by mkarchiso" \
             -no-emul-boot -boot-load-size 4 -boot-info-table \
             -publisher "Arch Linux <archlinux.org>" \
             -A "Arch Linux Live/Rescue CD" \
@@ -414,7 +465,7 @@ command_img () {
        isohybrid "${imgname}"
        md5sum "${imgname}" > "${imgname}".md5
     else
-		echo "Invalid image type '$IMG_TYPE' specified"
+		error "Invalid image type '$IMG_TYPE' specified"
 		exit 1
 	fi
 }
@@ -422,8 +473,14 @@ command_img () {
 if [ "${command_name}" = "install" -o "${command_name}" = "all" ]; then
 	command_install
 fi
+if [ "${command_name}" = "overlay" -o "${command_name}" = "all" ]; then
+    command_overlay
+fi
 if [ "${command_name}" = "squash" -o "${command_name}" = "all" ]; then
 	command_squash
+fi
+if [ "${command_name}" = "imgprepare" -o "${command_name}" = "all" ]; then
+    command_imgprepare
 fi
 if [ "${command_name}" = "img" -o "${command_name}" = "all" ]; then
 	command_img
