Copied archiso-live list folder and overlay folder into arch-mini profile. Updated modatabase script so you use .lzm and tell it what folder to update modules in. Using jensp idea for abs also.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/configs/arch-mini/overlay/usr/bin/arch2lzm b/configs/arch-mini/overlay/usr/bin/arch2lzm
--- a/configs/arch-mini/overlay/usr/bin/arch2lzm
+++ b/configs/arch-mini/overlay/usr/bin/arch2lzm
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# arch2sqfs - convert Archlinux packages to LiveCD modules for zenarch.
+# arch2lzm - convert Archlinux packages to LiveCD modules for archlive.
 #
 # Author: Christopher Rogers (aka Godane) <slaxemulator@gmail.com>
 #
@@ -9,7 +9,7 @@
 
 if [ "$1" = "" ]; then
    echo
-   echo "Download and convert local cache Archlinux's PKG.TAR.GZ package and deps into .sqfs compressed module"
+   echo "Download and convert local cache Archlinux's PKG.TAR.GZ package and deps into .LZM compressed module"
    echo "usage: $0 [option] common_package_name"
    echo "		option: "
    echo "		merge - cleans and download all new packages to cache "
@@ -17,7 +17,7 @@ if [ "$1" = "" ]; then
    echo "		(Ex. $0 merge xfce4)"
    echo
    echo "		update - updates the module you ask for "
-   echo "		(Ex. $0 update 01-core.sqfs" 
+   echo "		(Ex. $0 update 02_devel.lzm" 
    echo
    echo "		clean - cleans the cache"
    echo
@@ -26,15 +26,12 @@ if [ "$1" = "" ]; then
    echo " 		pkg - make a module of a package only "
    echo " 		(Ex. $0 pkg xchat)"
    echo 
-   echo "		aur - like pkg option but uses yaourt instend of pacman "
-   echo "		(Ex. $0 aur xchat)"
-   echo
    echo "		addlist - add packages to a module based on a list"
-   echo "		(Ex. $0 addlist module.sqfs list)"
+   echo "		(Ex. $0 addlist module.lzm list)"
    echo "		NOTE: list is a text file"
    echo
    echo "		removelist - remove packages from a module based on a list"
-   echo "		(Ex. $0 removelist module.sqfs list)"
+   echo "		(Ex. $0 removelist module.lzm list)"
    echo "		NOTE: list is a text file"
    echo
    echo	"		updateonly - makes updateonly module of current system"
@@ -47,8 +44,11 @@ if [ "$1" = "" ]; then
    echo "		NOTE: Only etc,home,opt,root,var folders are saved"
    echo
    echo "		mergelist - make a module based on a list of packages"
-   echo "		(Ex. $0 mergelist module.sqfs list)"
+   echo "		(Ex. $0 mergelist module.lzm list)"
    echo 
+   echo "		aur - build packages in aur unsupported"
+   echo "		(Ex. $0 aur package)"
+   echo
    exit 1
 fi
 
@@ -58,8 +58,10 @@ allow_only_root
 
 #touch $(pwd)/empty 2>/dev/null && rm -f $(pwd)/empty 2>/dev/null
 
-TMPDIR=/tmp/pkg2sqfs$$
+TMPDIR=/tmp/pkg2lzm$$
 CACHE=/tmp/cache$$
+
+mkdir -p /var/cache/pacman/pkg
 
 if [ -f /var/lib/pacman/db.lck ]; then
    rm -f /var/lib/pacman/db.lck # remove db.lck if script is cancel before finishing
@@ -85,8 +87,8 @@ merge()
 	pacman -U -d -r $TMPDIR $FILE
 	done
 	
-	DESTINATION="$(pwd)/$(basename $1).sqfs"
-	mksquashfs $TMPDIR $DESTINATION -b 64KB > mksquashfs.log
+	DESTINATION="$(pwd)/$(basename $1).lzm"
+	/sbin/mksquashfs $TMPDIR $DESTINATION -b 128kB > mksquashfs.log
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
 	exit
@@ -101,7 +103,7 @@ merge()
 
 changes()
 {
-	MODULE=$(basename "$1" .sqfs).sqfs
+	MODULE=$(basename "$1" .lzm).lzm
 	TMPDIR=/mnt/live/memory/tmp$$
 	CHANGES=/mnt/live/memory/changes
 
@@ -120,11 +122,11 @@ changes()
 		rm -rf $TMPDIR/var/run
 	fi
 	if [ "$1" = "" ]; then
-	DESTINATION="$(pwd)"/"changes-$(date +'%y.%m.%d.%H.%M').sqfs"
+	DESTINATION="$(pwd)"/"changes-$(date +'%y.%m.%d.%H.%M').lzm"
 	else
 	DESTINATION="$(pwd)/$MODULE"
 	fi
-	mksquashfs $TMPDIR $DESTINATION -b 64KB > mksquashfs.log
+	/sbin/mksquashfs $TMPDIR $DESTINATION -b 128kB > mksquashfs.log
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
 	exit
@@ -149,10 +151,10 @@ mergelist()
 	
 	PKG=$(ls $CACHE/*.pkg.tar.gz)
 	pacman -U --needed -d -r $TMPDIR $PKG
-	MODULE=$(basename "$1" .sqfs).sqfs
+	MODULE=$(basename "$1" .lzm).lzm
 	
 	DESTINATION="$(pwd)/$MODULE"
-	mksquashfs $TMPDIR $DESTINATION -b 64KB > mksquashfs.log
+	/sbin/mksquashfs $TMPDIR $DESTINATION -b 128kB > mksquashfs.log
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
 	exit
@@ -166,8 +168,8 @@ mergelist()
 
 removelist()
 {
-	MODULE=$(basename "$1" .sqfs).sqfs
-	TMPDIR=/mnt/live/memory/tmp$$
+	MODULE=$(basename "$1" .lzm).lzm
+	TMPDIR=/tmp/tmp$$
 	IMAGES=/mnt/live/memory/images
 	UNION=$TMPDIR/union
 	CHANGES=$TMPDIR/changes
@@ -177,12 +179,26 @@ removelist()
 	mkdir -p $UNION
 	mkdir -p $CHANGES
 	
+	if [ "$(cmdline_parameter aufs)" ]; then
+	modprobe aufs
+    if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
 	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
-	sync
+	else
+	modprobe unionfs
+	if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+    mount -t unionfs -o dirs=$CHANGES=rw:$IMAGES/$MODULE=ro none $UNION
+	fi
+	#sync
 	
 	cat $2 | grep -v "^#" | while read PKGNAME; do
 	if [ "$PKGNAME" = update ]; then
-		pacman -Su -d -r $UNION --noconfirm
+		pacman -Syu -d -r $UNION --noconfirm
 	else
 		pacman -R -r $UNION "$PKGNAME" --noconfirm
 	fi
@@ -191,13 +207,13 @@ removelist()
 	rm -R $UNION/var/lib/pacman/sync/*
 	
 	DESTINATION="$(pwd)/$MODULE"
-	mksquashfs $UNION $DESTINATION -b 64KB > mksquashfs.log
+	/sbin/mksquashfs $UNION $DESTINATION -b 128kB > mksquashfs.log
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
 	exit
 	fi
 	
-	umount -l $TMPDIR/union
+	umount $TMPDIR/union
 	echo $DESTINATION
 	chmod 0755 $DESTINATION
 }
@@ -206,39 +222,11 @@ removelist()
 #{
 #	pacman -Qs --database /mnt/live/memory/iamges/*/var/lib/pacman/local $1
 #}
-updateall()
-{
-	MODULE=$(basename "$1" .sqfs).sqfs
-	IMAGES=/mnt/live/memory/images
-	TMPDIR=/mnt/live/memory/tmp$$
-	CHANGES=$TMPDIR/changes
-	UNION=$TMPDIR/union
-	
-	if [ -d $TMPDIR ]; then
-	umount -n -l $UNION 2>/dev/null
-	rm -Rf $TMPDIR
-	fi
-	
-	if [ ! -d $IMAGES/$MODULE ]; then
-		echo "Module may not exist in union."
-	fi
-	mkdir -p $CHANGES/var/lib/pacman/local
-	mkdir -p $UNION
-
-	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
-	if [ $? -ne 0 ]; then 
-	echo "Error building union."
-	exit
-	fi
-	
-	
-	
-}
 
 addlist()
 {
-	MODULE=$(basename "$1" .sqfs).sqfs
-	TMPDIR=/mnt/live/memory/tmp$$
+	MODULE=$(basename "$1" .lzm).lzm
+	TMPDIR=/tmp/tmp$$
 	IMAGES=/mnt/live/memory/images
 	UNION=$TMPDIR/union
 	CHANGES=$TMPDIR/changes
@@ -248,12 +236,26 @@ addlist()
 	mkdir -p $UNION
 	mkdir -p $CHANGES
 	
+	if [ "$(cmdline_parameter aufs)" ]; then
+	modprobe aufs
+    if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
 	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
-	sync
+	else
+	modprobe unionfs
+	if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+    mount -t unionfs -o dirs=$CHANGES=rw:$IMAGES/$MODULE=ro none $UNION
+	fi
+	#sync
 	
 	cat $2 | grep -v "^#" | while read PKGNAME; do
 	if [ "$PKGNAME" = update ]; then
-		pacman -Su -d -r $UNION --noconfirm
+		pacman -Syu -d -r $UNION --noconfirm
 	else
 		pacman -Sw -d "$PKGNAME" --noconfirm
 		PKG=$(ls /var/cache/pacman/pkg/$PKGNAME-[0-9]*.pkg.tar.gz)
@@ -265,22 +267,22 @@ addlist()
 	rm -R $UNION/var/lib/pacman/sync/*
 	
 	DESTINATION="$(pwd)/$MODULE"
-	mksquashfs $UNION $DESTINATION -b 64KB > mksquashfs.log
+	/sbin/mksquashfs $UNION $DESTINATION -b 128kB > mksquashfs.log
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
 	exit
 	fi
 	
-	umount -l $TMPDIR/union
+	umount $TMPDIR/union
 	echo $DESTINATION
 	chmod 0755 $DESTINATION
 }
 
 pkg()
 {
-	TMPDIR="$(pwd)/pkg2sqfs$$"
+	TMPDIR="$(pwd)/pkg2lzm$$"
 	mkdir -p $TMPDIR/var/lib/pacman/local
-	#sync
+	sync
 	
 	#if [ $(whereis yaourt) ]; then
 	pacman -Sw "$1" --noconfirm
@@ -293,8 +295,36 @@ pkg()
 	
 	echo "Creating module ..."
 
-	DESTINATION="$(pwd)/$(basename $PKG .pkg.tar.gz).sqfs"
-	mksquashfs $TMPDIR $DESTINATION -b 64KB > mksquashfs.log
+	DESTINATION="$(pwd)/$(basename $PKG .pkg.tar.gz).lzm"
+	/sbin/mksquashfs $TMPDIR $DESTINATION -b 128kB > mksquashfs.log
+	
+	if [ $? -ne 0 ]; then 
+	echo "Error building module"
+	exit
+	fi
+	echo $DESTINATION
+	chmod 0755 $DESTINATION
+}
+
+aur()
+{
+	TMPDIR="$(pwd)/pkg2lzm$$"
+	mkdir -p $TMPDIR/var/lib/pacman/local
+	sync
+	
+	#if [ $(whereis yaourt) ]; then
+	yaourt -Sw "$1" --noconfirm
+	PKG=$(ls /var/cache/pacman/pkg/$1-[0-9]*.pkg.tar.gz)
+	yaourt -U -d -r $TMPDIR $PKG
+	#else
+	#pacman -Sw "$1" --noconfirm
+	#pacman -U -d -r $TMPDIR $PKG
+	#fi
+	
+	echo "Creating module ..."
+
+	DESTINATION="$(pwd)/$(basename $PKG .pkg.tar.gz).lzm"
+	/sbin/mksquashfs $TMPDIR $DESTINATION -b 128kB > mksquashfs.log
 	
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
@@ -306,15 +336,15 @@ pkg()
 
 local()
 {
-	TMPDIR="$(pwd)/pkg2sqfs$$"
+	TMPDIR="$(pwd)/pkg2lzm$$"
 	mkdir -p $TMPDIR/var/lib/pacman/local
 	PKG=$(ls $1-[0-9]*.pkg.tar.gz)
 	pacman -U -d -r $TMPDIR $PKG
 	
 	echo "Creating module ..."
 
-	DESTINATION="$(pwd)/$(basename $PKG .pkg.tar.gz).sqfs"
-	mksquashfs $TMPDIR $DESTINATION -b 64KB > mksquashfs.log
+	DESTINATION="$(pwd)/$(basename $PKG .pkg.tar.gz).lzm"
+	/sbin/mksquashfs $TMPDIR $DESTINATION -b 128kB > mksquashfs.log
 
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
@@ -331,35 +361,7 @@ clean()
 
 sync()
 {
-	pacman -Sy
-}
-
-aur()
-{
-	TMPDIR="$(pwd)/pkg2sqfs$$"
-	mkdir -p $TMPDIR/var/lib/pacman/local
-	#sync
-	
-	#if [ $(whereis yaourt) ]; then
-	yaourt -Sw "$1" --noconfirm
-	PKG=$(ls /var/cache/pacman/pkg/$1-[0-9]*.pkg.tar.gz)
-	yaourt -U -d -r $TMPDIR $PKG
-	#else
-	#pacman -Sw "$1" --noconfirm
-	#pacman -U -d -r $TMPDIR $PKG
-	#fi
-	
-	echo "Creating module ..."
-
-	DESTINATION="$(pwd)/$(basename $PKG .pkg.tar.gz).sqfs"
-	mksquashfs $TMPDIR $DESTINATION -b 64KB > mksquashfs.log
-	
-	if [ $? -ne 0 ]; then 
-	echo "Error building module"
-	exit
-	fi
-	echo $DESTINATION
-	chmod 0755 $DESTINATION
+	pacman -Syy
 }
 
 updateonly()
@@ -372,24 +374,39 @@ updateonly()
 	mkdir -p $DBPATH
 	mkdir -p $CHANGES
 	mkdir -p $UNION
-	MODULE=$(basename "$1" .sqfs).sqfs
+	MODULE=$(basename "$1" .lzm).lzm
 	cp -aR /var/lib/pacman/local/* $DBPATH
+	
+    if [ "$(cmdline_parameter aufs)" ]; then
+	modprobe aufs
+    if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
 	mount -t aufs -o br:$CHANGES=rw:$DB=rr aufs $UNION
+	else
+	modprobe unionfs
+	if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+    mount -t unionfs -o dirs=$CHANGES=rw:$DB=ro none $UNION
+	fi
 	#sync
 	pacman -Syu --noconfirm -d -r $UNION
 	
 	echo "Creating module ..."
 	
-	umount -f $UNION
+	umount -l $UNION
 	if [ "$1" = "" ]; then
-	DESTINATION="$(pwd)"/"update-$(date +'%y.%m.%d.%H.%M').sqfs"
+	DESTINATION="$(pwd)"/"update-$(date +'%y.%m.%d.%H.%M').lzm"
 	else
 	DESTINATION="$(pwd)/$MODULE"
 	fi
 
 	rm -Rf $CHANGES/var/lib/pacman/sync/*
 	find $CHANGES -type f -name ".wh.*" -delete
-	mksquashfs $CHANGES $DESTINATION -b 64KB > mksquashfs.log
+	/sbin/mksquashfs $CHANGES $DESTINATION -b 128kB > mksquashfs.log
 
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
@@ -403,9 +420,9 @@ updateonly()
 	
 update()
 {
-	MODULE=$(basename "$1" .sqfs).sqfs
+	MODULE=$(basename "$1" .lzm).lzm
 	IMAGES=/mnt/live/memory/images
-	TMPDIR=/mnt/live/memory/tmp$$
+	TMPDIR=/tmp/updatemod
 	CHANGES=$TMPDIR/changes
 	UNION=$TMPDIR/union
 	
@@ -417,21 +434,37 @@ update()
 	if [ ! -d $IMAGES/$MODULE ]; then
 		echo "Module may not exist in union."
 	fi
-	mkdir -p $CHANGES/var/lib/pacman/local
+	mkdir -p $CHANGES
 	mkdir -p $UNION
 
+	if [ "$(cmdline_parameter aufs)" ]; then
+	modprobe aufs
+    if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
+	else
+	modprobe unionfs
+	if [ $? -ne 0 ]; then
+	echo "Error loading Union filesystem module."
+	exit 1
+    fi
+    mount -t unionfs -o dirs=$CHANGES=rw:$IMAGES/$MODULE=ro none $UNION
+	fi
 	mount -t aufs -o br:$CHANGES=rw:$IMAGES/$MODULE=rr aufs $UNION
 	if [ $? -ne 0 ]; then 
 	echo "Error building union."
 	exit
 	fi
-
+	
+	mkdir -p $UNION/var/lib/pacman
 	#sync
 	pacman -Syu --noconfirm -d -r $UNION
 
 	rm -Rf $UNION/var/lib/pacman/sync/*
 
-	mksquashfs $UNION $MODULE -b 64KB > mksquashfs.log
+	/sbin/mksquashfs $UNION $MODULE -b 128kB > mksquashfs.log
 
 	if [ $? -ne 0 ]; then 
 	echo "Error building module"
@@ -489,5 +522,4 @@ esac
 
 echo "Cleaning temporary files ..."
 rm -Rf $TMPDIR
-find -type d -name "pkg2sqfs*" -delete
 echo "Completed!"
