Updated shutdown-chakra and sysinit-chakra so install will be read and write on boot.

diff --git a/configs/archiso-live/overlay/etc/rc.d/functions.d/sysinit-chakra b/configs/archiso-live/overlay/etc/rc.d/functions.d/sysinit-chakra
--- a/configs/archiso-live/overlay/etc/rc.d/functions.d/sysinit-chakra
+++ b/configs/archiso-live/overlay/etc/rc.d/functions.d/sysinit-chakra
@@ -1,5 +1,6 @@
 # Functions used by rc.sysinit
-# Modified versions for larch live systems
+# These can be overwritten by sourcing another file, for example so that
+# modified versions for a live CD can be used.
 
 f_header ()
 {
@@ -14,42 +15,80 @@ f_header ()
 
 f_fscheck ()
 {
-    stat_busy "Initializing /etc/mtab"
-    #/bin/mount -n -o remount,rw /
+    status "Mounting Root Read-only" /bin/mount -n -o remount,ro /
 
-    /bin/rm -f /etc/mtab*
-
-    # Make entries for aufs/unionfs, tmpfs and live medium in /etc/mtab
-    grep "^aufs */ " /proc/mounts >>/etc/mtab
-    grep "^unionfs */ " /proc/mounts >>/etc/mtab
-    grep "^tmpfs */.livesys " /proc/mounts >>/etc/mtab
-    if [ -d /bootmnt/archlive.sqfs ]; then
-        grep " /bootmnt/archlive.sqfs " /proc/mounts >>/etc/mtab
-    fi
-
-    f_mountlocal
-    stat_done
-
-    if [ -z "$( cat /etc/fstab | grep "^#KEEP" )" ]; then
-        stat_busy "Generating fresh /etc/fstab"
-        /opt/larch-live/run/gen_fstab -l
+    if [ -x /sbin/fsck ]; then
+        stat_busy "Checking Filesystems"
+        if /bin/grep -qw quiet /proc/cmdline; then
+            /sbin/fsck -A -T -C -a -t $NETFS $FORCEFSCK >/dev/null 2>&1
+        else
+            /sbin/fsck -A -T -C -a -t $NETFS $FORCEFSCK 2>/dev/null
+        fi
+        fsckret=$?
+        if [ ${fsckret} -gt 1 ]; then
+            stat_fail
+            if [ $((${fsckret}&2)) -eq 2 ]; then
+                echo
+                echo "********************** REBOOT REQUIRED *********************"
+                echo "*                                                          *"
+                echo "* The system will be rebooted automatically in 15 seconds. *"
+                echo "*                                                          *"
+                echo "************************************************************"
+                echo
+                /bin/sleep 15
+            else
+                echo
+                echo "*****************  FILESYSTEM CHECK FAILED  ****************"
+                echo "*                                                          *"
+                echo "*  Please repair manually and reboot. Note that the root   *"
+                echo "*  file system is currently mounted read-only. To remount  *"
+                echo "*  it read-write type: mount -n -o remount,rw /            *"
+                echo "*  When you exit the maintenance shell the system will     *"
+                echo "*  reboot automatically.                                   *"
+                echo "*                                                          *"
+                echo "************************************************************"
+                echo
+                /sbin/sulogin -p
+            fi
+            echo "Automatic reboot in progress..."
+            /bin/umount -a
+            /bin/mount -n -o remount,ro /
+            /sbin/reboot -f
+            exit 0
+        fi
         stat_done
     fi
 
-    # now mount all the local filesystems
     stat_busy "Mounting Local Filesystems"
-    /bin/mount -a -t $NETFS
+    /bin/mount -n -o remount,rw /
+    /bin/rm -f /etc/mtab*
+    # make sure / gets written to /etc/mtab
+    /bin/mount -o remount,rw /
+
+    f_mountlocal
     stat_done
+}
+
+f_mountlocal ()
+{
+    # re-mount /proc , /sys  and usbfs so they can be written to /etc/mtab
+    /bin/umount /proc/bus/usb
+    if [ -e /proc/mounts ]; then
+        /bin/grep -e "/proc " -e "/sys " -e "/dev " /proc/mounts >> /etc/mtab
+    fi
+    if /bin/grep -qw usbfs /proc/filesystems; then
+        # Some people use custom permissions for their usbfs
+        if /bin/grep -v "^#" /etc/fstab | /bin/grep -qw /proc/bus/usb ; then
+            /bin/mount /proc/bus/usb
+        else
+            /bin/mount -t usbfs none /proc/bus/usb
+        fi
+    fi
+    # now mount all the local filesystems
+    /bin/mount -a -t $NETFS
 }
 
 f_swapon ()
 {
-    #+*** Copy session-save flag-file (if it exists)
-    [ -f /larch/nosave ] && cp /larch/nosave /.livesys
-    #-***
-
-    #*** Conditional swap activation
-    if [ -e /.livesys/swapon ]; then
-        status "Activating Swap" /sbin/swapon -a
-    fi
+    status "Activating Swap" /sbin/swapon -a
 }
