Adding support for making slitaz livecd.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/scripts/mkarchiso b/scripts/mkarchiso
--- a/scripts/mkarchiso
+++ b/scripts/mkarchiso
@@ -20,6 +20,7 @@ OVERLAY="${PROFILE}/overlay"
 EXCLUDE="${PROFILE}/exclude"
 ARCH=i686
 #ARCH=x86_64
+OS="archlinux"
 
 error () { echo -e "\033[1;31;40m!!! \033[1;37;40m$@\033[1;0m"; }
 warn ()  { echo -e "\033[1;33;40m*** \033[1;37;40m$@\033[1;0m"; }
@@ -107,10 +108,12 @@ if [ "$EUID" != "0" ]; then
 	exit 1
 fi
 
-if [ -f "${PROFILE}/pacman.conf-${ARCH}" ]; then
-	PACMANCONF="${PROFILE}/pacman.conf-${ARCH}"
-else
-	PACMANCONF="/etc/pacman.conf"
+if [ "${OS}" = "archlinux" ]; then
+    if [ -f "${PROFILE}/pacman.conf-${ARCH}" ]; then
+        PACMANCONF="${PROFILE}/pacman.conf-${ARCH}"
+    else
+        PACMANCONF="/etc/pacman.conf"
+    fi
 fi
 
 command_name="${1}"
@@ -176,7 +179,7 @@ remove()
 	return
 }
 
-check()
+check_arch()
 {
 	if [ ! "$(pacman -Q aufs2)" ]; then
 		error "Aufs2 needs to be installed."
@@ -311,7 +314,77 @@ command_livebackup_imgprepare()
 	basedir=${INSTROOT}
 	[ "${INSTROOT:0:1}" != "/" ] && basedir="$(pwd)/${INSTROOT}"
 	mkinitramfs -c "${CPIOCONFIG}" -k "${kernelver}" -g "${IMGROOT}/boot/initrd.img"
+}
 
+install_slitaz_union () {
+	source ${PROFILE}/tazpkg.conf
+	mkdir -p ${LOCALSTATE}/installed/
+	mkdir -p ${CACHE_DIR}
+	
+	tazpkg get-install-list $(pwd)/list/${mod}.list --root=${union} | tee -a ${buildlog}/${mod}-current.log
+}
+
+install_arch_union () {
+
+    if [ -e "${union}/var/lib/pacman/db.lck" ]; then
+        rm -f ${union}/var/lib/pacman/db.lck
+    fi
+
+    mkdir -p "${union}/var/lib/pacman"
+    # Remove /var/lib/pacman/local folder in case it just there.
+    # This will not remove it if anything is in /var/lib/pacman/local folder. 
+    # Only if its a empty folder.
+    if [ ! -d "${INSTROOT}/var/lib/pacman/sync/core" ]; then
+        pacman -Sy --noprogressbar --noconfirm --config "${PACMANCONF}" -fr "${union}"
+        rmdir --ignore-fail-on-non-empty ${INSTROOT}/var/lib/pacman/local
+    fi
+
+    if [ -d ${moduledir}/${mod}/var/lib/pacman/local ]; then
+        pacman -Q -r ${moduledir}/${mod} > ${packlist}/${mod}.old
+        pacman -Su -f --needed --noconfirm --config "${PACMANCONF}" -fr "${union}"
+    elif [ ! -d ${moduledir}/${mod}/var/lib/pacman/local ]; then
+        touch ${packlist}/${mod}.old
+
+        cat "$(pwd)/list/${mod}.list" | grep -v "^#" | while read pkgname; do
+            info "Installing package $pkgname"
+            pacman -S -f --needed --noconfirm --config "${PACMANCONF}" -r "$union" $pkgname | tee -a ${buildlog}/${mod}-current.log
+            if [ $? -ne 0 ]; then
+                warn "Package $pkgname not correctly installed"
+                cat ${buildlog}/${mod}-current.log >> ${buildlog}/${mod}-errors.log
+            fi
+        done
+
+        if [ -e "$(pwd)/list/${mod}.removelist" ]; then
+            cat "$(pwd)/list/${mod}.removelist" | grep -v "^#" | while read pkgname; do
+                info "Removing package $pkgname"
+                pacman -R -d -n --noprogressbar --needed --noconfirm --config "${PACMANCONF}" -r "$union" $pkgname &> /dev/null
+            done
+        fi
+    fi
+    
+    pacman -Q -r ${moduledir}/${mod} > ${packlist}/${mod}.new
+
+    if [ -f ${packlist}/${mod}.old ]; then
+        packagediff.py ${packlist}/${mod}.old ${packlist}/${mod}.new > ${packlist}/${mod}.list
+    fi
+
+    # Cleanup
+    info "Cleaning up image root files..."
+    find "${union}" -name *.pacnew -name *.pacsave -name *.pacorig -delete
+
+    # delete a lot of unnecessary cache/log files
+    # We don't have to delete stuff from /usr/share/doc if we are building archpwn module
+    if [ "${mod:4:7}" = "archpwn" ]; then
+        kill_dirs="var/cache/man var/cache/pacman var/log/* var/mail tmp/ initrd"
+    else
+        kill_dirs="var/cache/man var/cache/pacman var/log/* var/mail tmp/* initrd ${DELDIR}"
+    fi
+
+    for x in ${kill_dirs}; do
+        if [ -e "${union}/${x}" ]; then
+            rm -Rf "${union}/${x}"
+	fi
+    done
 
 }
 
@@ -373,10 +446,6 @@ command_install () {
 		info "Adding ${lastbr} as lower branch of union."
 		mount -o remount,mod:${lastbr}=rr+wh aufs ${union}
 		lastbr="${moduledir}/${mod}"
-
-		if [ -e "${union}/var/lib/pacman/db.lck" ]; then
-			rm -f ${union}/var/lib/pacman/db.lck
-		fi
 	
 		mkdir -p "${union}/var/lib/pacman"	
 
@@ -386,42 +455,10 @@ command_install () {
 		mknod ${union}/dev/null c 1 3 >/dev/null
 		mknod ${union}/dev/zero c 1 5 >/dev/null
 		
-		# Remove /var/lib/pacman/local folder in case it just there.
-		# This will not remove it if anything is in /var/lib/pacman/local folder. 
-		# Only if its a empty folder.
-		if [ ! -d "${INSTROOT}/var/lib/pacman/sync/core" ]; then
-			pacman -Sy --noprogressbar --noconfirm --config "${PACMANCONF}" -fr "${union}"
-			rmdir --ignore-fail-on-non-empty ${INSTROOT}/var/lib/pacman/local
-		fi
-
-		if [ -d ${moduledir}/${mod}/var/lib/pacman/local ]; then
-			pacman -Q -r ${moduledir}/${mod} > ${packlist}/${mod}.old
-			pacman -Su -f --needed --noconfirm --config "${PACMANCONF}" -fr "${union}"
-		elif [ ! -d ${moduledir}/${mod}/var/lib/pacman/local ]; then
-			touch ${packlist}/${mod}.old
-
-			cat "$(pwd)/list/${mod}.list" | grep -v "^#" | while read pkgname; do
-				info "Installing package $pkgname"
-				pacman -S -f --needed --noconfirm --config "${PACMANCONF}" -r "$union" $pkgname | tee -a ${buildlog}/${mod}-current.log
-
-				if [ $? -ne 0 ]; then
-					warn "Package $pkgname not correctly installed"
-					cat ${buildlog}/${mod}-current.log >> ${buildlog}/${mod}-errors.log
-				fi
-			done
-
-			if [ -f "$(pwd)/list/${mod}.removelist" ]; then
-				cat "$(pwd)/list/${mod}.removelist" | grep -v "^#" | while read pkgname; do
-					info "Removing package $pkgname"
-					pacman -R -d -n --noprogressbar --needed --noconfirm --config "${PACMANCONF}" -r "$union" $pkgname &> /dev/null
-				done
-			fi
-		fi
-
-		pacman -Q -r ${moduledir}/${mod} > ${packlist}/${mod}.new
-
-		if [ -f ${packlist}/${mod}.old ]; then
-			packagediff.py ${packlist}/${mod}.old ${packlist}/${mod}.new > ${packlist}/${mod}.list
+		if [ "${OS}" = "archlinux" ]; then
+			install_arch_union
+		elif [ "${OS}" = "slitaz" ]; then
+			install_slitaz_union
 		fi
 
 		if [ -e "${union}/etc/ld.so.conf" ]; then
@@ -554,8 +591,21 @@ command_overlay () {
 	chmod 0755 "${IMGROOT}/${CDNAME}/optional/overlay.${EXT}"
 }
 
+command_squash_slitaz () {
+	info "Generating SquashFS image"
+	info "Creating modules procede..."
+
+        for DIR in $MODULES; do
+		MOD="$(basename $DIR).${EXT}"
+		#if [ ! "$(find "$IMGROOT/$CDNAME" -name "$MOD")" ]; then
+			mksquashfs ${moduledir}/$DIR ${moduleplace}/$MOD -noappend ${MKOPTION}
+			chmod 0755 ${moduleplace}/$MOD
+		#fi
+	done
+}
+
 # Squash is the next step.
-command_squash () {
+command_squash_arch () {
 	info "Generating SquashFS image"
 	info "Creating modules procede..."
 
@@ -692,48 +742,65 @@ command_img () {
 	fi
 }
 
-if [ "${command_name}" = "install" -o "${command_name}" = "all" ]; then
-	check
-	command_install
-fi
+    if [ "${command_name}" = "install" -o "${command_name}" = "all" ]; then
+        #check_arch
+        command_install
+    fi
 
-if [ "${command_name}" = "overlay" -o "${command_name}" = "all" ]; then
-	check
-	command_overlay
-fi
+    if [ "${command_name}" = "overlay" -o "${command_name}" = "all" ]; then
+        #check_arch
+        command_overlay
+    fi
 
-if [ "${command_name}" = "squash" -o "${command_name}" = "all" ]; then
-	check
-	command_squash
-fi
+if [ "${OS}" = "archlinux" ]; then
+    if [ "${command_name}" = "squash" -o "${command_name}" = "all" ]; then
+        #check_arch
+        command_squash_arch
+    fi
 
-if [ "${command_name}" = "imgprepare" -o "${command_name}" = "all" ]; then
-	check
-	command_imgprepare
-fi
+    if [ "${command_name}" = "imgprepare" -o "${command_name}" = "all" ]; then
+        #check_arch
+        command_imgprepare
+    fi
 
-if [ "${command_name}" = "img" -o "${command_name}" = "all" ]; then
-	check
+    if [ "${command_name}" = "img" -o "${command_name}" = "all" ]; then
+	#check_arch
 	command_img
-fi
+    fi
 
-if [ "${command_name}" = "livebackup" ]; then
-	check
-	command_livebackup
-	if [ -d "${OVERLAY}" ]; then
-		command_overlay
+    if [ "${command_name}" = "livebackup" ]; then
+        check_arch
+        command_livebackup
+        if [ -d "${OVERLAY}" ]; then
+            command_overlay
 	fi
-	command_livebackup_imgprepare
-	command_img
-fi
+        command_livebackup_imgprepare
+        command_img
+    fi
 
-if [ "${command_name}" = "liveimg" ]; then
-	check
-	if [ -d "${OVERLAY}" ]; then
-		command_overlay
-	fi
-	command_livebackup_imgprepare
+    if [ "${command_name}" = "liveimg" ]; then
+        check_arch
+        if [ -d "${OVERLAY}" ]; then
+            command_overlay
+        fi
+        command_livebackup_imgprepare
+        command_img
+    fi
+elif [ "${OS}" = "slitaz" ]; then
+    if [ "${command_name}" = "squash" -o "${command_name}" = "all" ]; then
+        #check_arch
+        command_squash_slitaz
+    fi
+
+    if [ "${command_name}" = "imgprepare" -o "${command_name}" = "all" ]; then
+        #check_arch
+        command_imgprepare
+    fi
+
+    if [ "${command_name}" = "img" -o "${command_name}" = "all" ]; then
+	#check_arch
 	command_img
+    fi
 fi
 
 # vim:ts=4:sw=4:et:
