Added mount_tmpfs function to archiso hook and xfs kernel module to install/archiso hook. Added some deps for mythtv into 006_xlibs list for archiso-live profile.

diff --git a/archiso/hooks/archiso b/archiso/hooks/archiso
--- a/archiso/hooks/archiso
+++ b/archiso/hooks/archiso
@@ -36,6 +36,30 @@ _mnt_ext2_file()
     export LOOP_NUM=$(( $LOOP_NUM + 1 ))
 }
 
+_mnt_xfs_file()
+{
+    msg "::: Adding new real_root branch: ${1}"
+    /bin/modprobe -q loop max_loop=255 >/dev/null 2>&1
+    /bin/modprobe -q xfs >/dev/null 2>&1
+    mkdir -p ${2}
+    if ! /bin/losetup "/dev/loop${LOOP_NUM}" ${1} > /dev/null 2>&1; then
+        echo "ERROR: Cannot mount loop device /dev/loop${LOOP_NUM}"
+        echo "       Couldn't mount all addons"
+        break
+    fi
+    /bin/mount -t xfs "/dev/loop${LOOP_NUM}" ${2}
+    export LOOP_NUM=$(( $LOOP_NUM + 1 ))
+}
+
+mount_tmpfs () 
+{
+    if [ "x${ramdisk_size}" = "x" ]; then
+        ramdisk_size="75%"
+    fi
+    msg -n ":: Mounting tmpfs, size=${ramdisk_size}..."
+    mount -t tmpfs -o "size=${ramdisk_size}" tmpfs /tmpfs
+    msg "done."
+}
 
 # args: image file
 _mnt_squashfs()
@@ -62,10 +86,6 @@ run_hook ()
 {
 	export LOOP_NUM="0"
 	
-
-    if [ "x${ramdisk_size}" = "x" ]; then
-        ramdisk_size="60%"
-    fi
     
     if [ "x${bootiso}" != "x" ]; then
     	_mnt_cdimage ${BOOT_MOUNT}/${bootiso}
@@ -80,17 +100,22 @@ run_hook ()
     	_mnt_ext2_file "${BOOT_MOUNT}/initrd" "/tmpfs"
     fi
 
+	#if [ "x${changes}" != "x" ]; then
+	#	if [ -f "${BOOT_MOUNT}/${changes}" ]; then
+	#		msg -n ":: Mounting xfs file changes. "
+	#		_mnt_xfs_file "${BOOT_MOUNT}/${changes}" "/tmpfs"
+	#	fi
+	#fi
+
     if [ "${changes}" = "y" ]; then
 	if [ "${bootusb}" = "y" ]; then
 		if [ -d "${BOOT_MOUNT}/changes" ]; then
 			msg -n ":: Mounting changes. "
-			/bin/mount -o bind "${BOOT_MOUNT}/changes" "/tmpfs"
+			/bin/mount -o bind "${BOOT_MOUNT}/changes" "/tmpfs"			
 		fi
 	fi
     else
-	msg -n ":: Mounting tmpfs, size=${ramdisk_size}..."
-	mount -t tmpfs -o "size=${ramdisk_size}" tmpfs /tmpfs
-    	msg "done."
+	mount_tmpfs
     fi
     
     if [ "x${BOOT_MOUNT}" = "x" ]; then
@@ -109,7 +134,6 @@ run_hook ()
     msg ":: Mounting squashfs image"
     /bin/modprobe -q squashfs >/dev/null 2>&1
 
-    mkdir -p /tmpfs/changes
     msg ":: Mounting root (real_root) filesystem"
     if [ "${aufs}" = "y" ]; then
     /bin/modprobe -q aufs brs=1 >/dev/null 2>&1
@@ -118,7 +142,6 @@ run_hook ()
     /bin/modprobe -q unionfs >/dev/null 2>&1
     /bin/mount -t unionfs -o dirs=/tmpfs=rw none /real_root
     fi
-
     
     addon_dir="${BOOT_MOUNT}/addons"
 
@@ -144,7 +167,7 @@ run_hook ()
     else
 
     # always layer default configuration
-		_mnt_squashfs "${addon_dir}/overlay.sqfs"
+    _mnt_squashfs "${addon_dir}/overlay.sqfs"
 
     if [ -e "${addon_dir}/config" ]; then
         msg ":: Mounting addons"
@@ -168,20 +191,23 @@ fi
         echo 0 > /proc/sys/dev/cdrom/lock
         echo 0 > /proc/sys/dev/cdrom/autoeject
     fi
-	MEMORY=/mnt/live/memory
-	CHANGES=${MEMORY}/changes
-	mkdir -p /real_root/${CHANGES}
-	if [ -f "${BOOT_MOUNT}/initrd" ]; then
-		/bin/mount -o move /tmpfs /real_root/${CHANGES}
-	else
-		/bin/mount -o bind /tmpfs /real_root/${CHANGES}
-	fi
-	if [ "${bootusb}" = "y" ]; then
-		if [ "x${from}" != "x" ]; then
+
+    MEMORY=/mnt/live/memory
+    CHANGES=${MEMORY}/changes
+    mkdir -p /real_root/${CHANGES}
+
+    if [ -f "${BOOT_MOUNT}/initrd" ]; then
+	/bin/mount -o move /tmpfs /real_root/${CHANGES}
+    else
+	/bin/mount -o bind /tmpfs /real_root/${CHANGES}
+    fi
+
+    if [ "${bootusb}" = "y" ]; then
+	if [ "x${from}" != "x" ]; then
     		mkdir -p /real_root/device
-			mount -w -o move "/bootmnt" "/real_root/device"
-		fi
+		mount -w -o move "/bootmnt" "/real_root/device"
 	fi
+    fi
 	
     if [ "${norootcopy}" = "y" ]; then
     	msg ":: no copying of rootcopy"
@@ -189,8 +215,8 @@ fi
 	cp -af ${BOOT_MOUNT}/rootcopy/* /real_root 2>/dev/null # may be empty
     fi
 
-	mkdir -p /real_root/bootmnt
-	/bin/mount -o move ${BOOT_MOUNT} /real_root/bootmnt
+    mkdir -p /real_root/bootmnt
+    /bin/mount -o move ${BOOT_MOUNT} /real_root/bootmnt
 
     if [ "${break}" = "y" ]; then
         echo ":: Break requested, type 'exit' to resume operation"
@@ -207,12 +233,12 @@ fi
 	#/bin/mount -o bind /sys /real_root/sys
     #/bin/mount -o bind /proc /real_root/proc
     
-	ROOT=/real_root
+    ROOT=/real_root
 
-    	/bin/mkdir -p $ROOT/dev 2>&1 >/dev/null
-    	/bin/mknod $ROOT/dev/console c 5 1 2>&1 >/dev/null
-    	/bin/mknod $ROOT/dev/null c 1 3 2>&1 >/dev/null
-    	/bin/mknod $ROOT/dev/zero c 1 5 2>&1 >/dev/null
+    /bin/mkdir -p $ROOT/dev 2>&1 >/dev/null
+    /bin/mknod $ROOT/dev/console c 5 1 2>&1 >/dev/null
+    /bin/mknod $ROOT/dev/null c 1 3 2>&1 >/dev/null
+    /bin/mknod $ROOT/dev/zero c 1 5 2>&1 >/dev/null
 
     exec /bin/run-init -c /dev/console /real_root /sbin/init ${CMDLINE}
 }
